# Generated by Django 3.2.5 on 2023-03-01 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('article_file', models.FileField(upload_to='uploads/', verbose_name='فایل')),
                ('department', models.CharField(max_length=256, verbose_name='نام گروه ')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.CharField(max_length=256, verbose_name='استاد راهنما')),
                ('supervisor_approve', models.BooleanField(verbose_name='تایید استاد راهنما')),
                ('head_of_department_approve', models.BooleanField(verbose_name='تایید مدیر گروه')),
                ('department_approve', models.BooleanField(verbose_name='تایید گروه')),
                ('deputy_of_education_approve', models.BooleanField(verbose_name='تایید معاونت آموزشی ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=140)),
                ('author', models.CharField(choices=[('supervisor', 'استاد راهنما'), ('head_of_department', 'مدیر گروه'), ('deputy_of_education', 'معاونت آموزشی'), ('professor', 'استاد گروه ')], max_length=256, verbose_name='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
            ],
        ),
    ]
